### ISSUE TITLE
ENOENT: no such file or directory in Windows

### ISSUE THREAD

**Issue by jtn-d** [alwaysonlinetxm/rollup-plugin-fill-html#1]
I like simplicity of implementing hashing, unfortunately it doesn't work in Windows. It uses hardcoded segment separator ('/') instead of path.sep.

ENOENT: no such file or directory, scandir 'C:\xxx\dist\bundle.7052a28fe691982e9d8e3649e7e9ff7d.j'
Error: ENOENT: no such file or directory, scandir 'C:\xxx\dist\bundle.7052a28fe691982e9d8e3649e7e9ff7d.j'
    at Error (native)
    at Object.fs.readdirSync (fs.js:951:18)
    at traverse (C:\xxx\node_modules\rollup-plugin-fill-html\dist\index.cjs.js:102:20)
    at Object.onwrite (C:\xxx\node_modules\rollup-plugin-fill-html\dist\index.cjs.js:157:7)
    at C:\xxx\node_modules\rollup\src\rollup.js:123:38
    at next (C:\xxx\node_modules\rollup\src\utils\promise.js:6:10)
    at C:\xxx\node_modules\rollup\src\utils\promise.js:10:33
Type rollup --help for help, or visit https://github.com/rollup/rollup/wiki
error Command failed with exit code 1.

**Comment by alwaysonlinetxm** [comment]
@jtn-d Can you show me a simple example which can reproduce this issue？

**Comment by jtn-d** [comment]
Like in your hash example:
```
export default {
  entry: 'src/index.js',
  dest: 'dist/bundle-[hash].js',
  plugins: [
    html({
      template: 'src/index.html'
    })
    ...
  ]
};
```

**Comment by alwaysonlinetxm** [comment]
@jtn-d As I don't know what your code and project directory is like, so I can't find out where your problem is. There is my advice: I have create an [example](https://github.com/alwaysonlinetxm/rollup-plugin-fill-html/tree/master/examples), and I have made it work well in my mac. You can clone my code to run in your windows, and tell me what problem you meet if it doesn't work.

**Comment by jtn-d** [comment]
The issue is not project dependent. So exact same error occurs with your project:

$ rollup -c -w
bundling...
ENOENT: no such file or directory, scandir 'C:\XXX\rollup-plugin-fill-html\examples\dist\bundle-9cfd9ac56622b9c793c846f64efee5b4.j'

**Comment by alwaysonlinetxm** [comment]
@jtn-d Got this. I think it's something to do with writeFileSync api in windows. But I don't have a window compute nowr, so I will fix this as soon as I get one.

**Comment by alwaysonlinetxm** [comment]
@jtn-d Hi, your problem has been resolved by @jacovc86 , you can update `rollup-plugin-fill-html` and have a try.
