### ISSUE TITLE
Breaks under latest rollup version due to change in configuration structure

### ISSUE THREAD

**Issue by lirsacc** [alwaysonlinetxm/rollup-plugin-fill-html#4]
Seems this is not compatible with the latest rollup version released [a few days ago](https://github.com/rollup/rollup/blob/master/CHANGELOG.md#0480).

Running `rollup@0.48.2` alongside `rollup-plugin-fill-html@1.0.5` I get the following error:

```
[!] Error: ENOENT: no such file or directory, scandir ''
Error: ENOENT: no such file or directory, scandir ''
    at Object.fs.readdirSync (fs.js:910:18)
    at traverse (/Users/lirsacc/projects/sample-project/node_modules/rollup-plugin-fill-html/dist/index.cjs.js:102:20)
    at Object.onwrite (/Users/lirsacc/projects/sample-project/node_modules/rollup-plugin-fill-html/dist/index.cjs.js:162:4)
    at /Users/lirsacc/projects/sample-project/node_modules/rollup/dist/rollup.js:10609:40
    at next (/Users/lirsacc/projects/sample-project/node_modules/rollup/dist/rollup.js:148:27)
    at /Users/lirsacc/projects/sample-project/node_modules/rollup/dist/rollup.js:152:48
    at <anonymous>
```

I've tracked it down to https://github.com/alwaysonlinetxm/rollup-plugin-fill-html/blob/master/src/index.js#L32 where `config.dest` is now `undefined` and the file path is now available under `config.file`. I guess this applies to the multi-targets case a couple lines down as well.

Some details on the config changes can be found in [this gist](https://gist.github.com/Rich-Harris/d472c50732dab03efeb37472b08a3f32) according to rollup's changelog.

Sorry for the noise in case you're already working on that; if not I could also make a PR with a fix if I find some time over the weekend.

**Comment by alwaysonlinetxm** [comment]
@lirsacc Thank you for your reminding！I have just found the problem from the newest release of rollup yestoday, but have not got time to fix this, as I am a little busy recently. So,it will be very kind of you if you cold make a PR to fix this!

**Comment by lirsacc** [comment]
Done, see #5.

**Comment by alwaysonlinetxm** [comment]
@lirsacc Have merged.
