### ISSUE TITLE
Support type="module"

### ISSUE THREAD

**Issue by funkybob** [alwaysonlinetxm/rollup-plugin-fill-html#8]
[Most browsers](https://caniuse.com/#feat=es6-module) now support <script type="module">
It would be great if this were an options for this utility.

Sure, ideally it would somehow know which to use for which, but to begin with I figure:
a) a setting for all generated bundles to use
b) a setting for externals [or per external?]

**Comment by alwaysonlinetxm** [comment]
@funkybob  Would you like to make a PR for this?

**Comment by funkybob** [comment]
So my PR has been sitting  there since May 15... anything else you'd like me to fix with it?
